### ISSUE TITLE
언어 통일

### ISSUE THREAD

**Issue by obongsik** [SSWU-ServerSystem/3team#3]
## 💡 목적
회원 가입, 로그인 등 다양한 화면에서 입력 칸과 버튼의 메시지가 한글과 영어로 혼재되어 있다. 한글 또는 영어 중 하나로 통일하여 UI의 일관성을 높이고, 사용자 경험을 개선하려고 한다.

## 🌿  작업 상세 내용
 1. 회원 가입, 로그인, 게시판, 채팅, 문의 화면에서 모든 버튼 및 입력 칸 메시지의 언어 통일.
 2. 한글 또는 영어 중 하나를 선택하여 일관성 있게 적용.
 3. 각 화면의 변경 사항 확인 및 UI 테스트.

## 참고 사항
통일되지 않은 페이지 확인 후 정리

**Comment by ljjyu** [comment]
@obongsik 한글로 통일하여 작업하겠습니다

**Comment by obongsik** [comment]
작업 완료
